In [6]:
import torch

In [9]:
x = torch.empty(5,3)
x = torch.rand(5,3)
x

tensor([[0.0670, 0.5546, 0.8513],
        [0.0020, 0.6998, 0.7319],
        [0.4520, 0.6778, 0.0698],
        [0.8050, 0.9040, 0.2644],
        [0.8531, 0.0185, 0.2485]])

In [11]:
x = torch.zeros(5,3,dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
x = torch.Tensor(5,3)
x = torch.Tensor([5.5,3.3])
x

tensor([5.5000, 3.3000])

In [17]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
y =torch.randn_like(x,dtype = torch.double)
y

tensor([[-0.9798, -0.3961, -0.4842],
        [-0.3704,  0.1625,  1.1948],
        [-1.3064,  0.6484, -1.5039],
        [ 0.4625,  0.5608,  1.1089],
        [-0.1834,  0.9199, -0.3426]], dtype=torch.float64)

In [19]:
y.size() 

torch.Size([5, 3])

In [20]:
y = torch.rand(5,3)
y

tensor([[0.0959, 0.7381, 0.0215],
        [0.9136, 0.3406, 0.9253],
        [0.2135, 0.8286, 0.3030],
        [0.5867, 0.9256, 0.7991],
        [0.3808, 0.0652, 0.6389]])

In [21]:
z = x + y
z

tensor([[1.0959, 1.7381, 1.0215],
        [1.9136, 1.3406, 1.9253],
        [1.2135, 1.8286, 1.3030],
        [1.5867, 1.9256, 1.7991],
        [1.3808, 1.0652, 1.6389]])

In [23]:
z = torch.add(x,y)
z

tensor([[1.0959, 1.7381, 1.0215],
        [1.9136, 1.3406, 1.9253],
        [1.2135, 1.8286, 1.3030],
        [1.5867, 1.9256, 1.7991],
        [1.3808, 1.0652, 1.6389]])

In [24]:
y.add_(x)
y = y + x

In [34]:
a = torch.rand(4,4)
b = torch.rand(4,4)
a

tensor([[0.1478, 0.1119, 0.1024, 0.7472],
        [0.0211, 0.9978, 0.3442, 0.1810],
        [0.7952, 0.7711, 0.0349, 0.9747],
        [0.6208, 0.0676, 0.9882, 0.4577]])

In [35]:
#c = a + b
c = torch.empty(4,4)
torch.add(a,b, out  = c)
c

tensor([[0.3016, 0.2992, 0.3976, 1.4308],
        [0.9048, 1.2460, 0.7338, 0.6622],
        [1.1447, 1.4413, 0.7376, 1.3071],
        [1.1553, 0.0931, 1.1994, 0.4890]])

In [49]:
a[:,1]

tensor([0.1119, 0.9978, 0.7711, 0.0676])

In [50]:
a.shape

torch.Size([4, 4])

In [51]:
a.view(-1,8)

tensor([[0.1478, 0.1119, 0.1024, 0.7472, 0.0211, 0.9978, 0.3442, 0.1810],
        [0.7952, 0.7711, 0.0349, 0.9747, 0.6208, 0.0676, 0.9882, 0.4577]])

In [52]:
a[0,0].item()

0.14779877662658691

In [54]:
y = x.numpy()
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [55]:
# tensor -> array : .numpy()
# array -> : torch.from_numpy(array) 
import numpy as np 

In [56]:
a = np.ones(3)
a

array([1., 1., 1.])

In [59]:
b =torch.from_numpy(a)
b

tensor([1., 1., 1.], dtype=torch.float64)

In [60]:
#ktra co gpu ko
device = torch.cuda.is_available()
device

False

In [61]:
# Thuc hien phep toan tren GPU 
if torch.cuda.is_available() : 
    device = torch.device("cuda")
    y = torch.ones_like(a,device = device)
    a = a.to(device)
    z = a + y
    print(z)
    

In [ ]:
# Thuc hien tren CPU : .cpu() -> Chuyen ve tinh toan tren CPU